import { Inter } from "next/font/google";
import "./globals.css";
import Logo from "./Logo";
import Sidebar from "./Sidebar";
import Header from "./Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex relative">
          <div className="h-screen border md:hidden lg:block hidden  top-0 bottom-0 sticky">
            <Logo />
            <Sidebar />
          </div>
          <div className="w-full relative">
            <Header />
            <div className="p-8 overflow-y-scroll max-h-[700px]">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
